In [1]:
import numpy as np

# Shape Manipulation

The shape of a basic array can be changed according to the requirement using NumPy library functions. These array shape manipulation methods really come in handy during the data wrangling phase and is used extensively by Data Scientists.
Following are some common methods for manipulating shapes:
- Ravel/Flatten
- Reshape
- Resize

Let’s look at each in the following:

In [2]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print (trials)
print ()
print (trials.ndim)
print ()
print (trials.shape)
print ()
print (trials.size)

[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

2

(2, 6)

12


### Ravel
This function returns a flattened one-dimensional array. The returned array will have the same type as that of the input array. The function takes one parameter.

In [3]:
print ("Ravel-ed Trial : ", trials.ravel())
print ()
print ("Ravel-ed Trial Dimension : ", trials.ravel().ndim)
print ("Ravel-ed Trial Shape : ", trials.ravel().shape)
print ()
print ("Original Dimension : ", trials.ndim)
print ("Original Shape : ", trials.shape)

Ravel-ed Trial :  [10 15 17 26 13 19 12 11 21 24 14 23]

Ravel-ed Trial Dimension :  1
Ravel-ed Trial Shape :  (12,)

Original Dimension :  2
Original Shape :  (2, 6)


- **The ravel function flattens the dataset into a single row.**
- **It will *not* modify the original array**

In [4]:
trails_new  = trials.ravel()
print (trails_new)
print (trails_new.shape)
print (trails_new.size)

[10 15 17 26 13 19 12 11 21 24 14 23]
(12,)
12


### Reshape
This function gives a new shape to an array without changing the data.

In [5]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print (trials)
print ()

print ("Original Array's Shape : ", trials.shape)
print ()

print ("Re-shaped Array : \n", trials.reshape(3,4)) 
print ("Re-shaped Array's Shape : ", trials.reshape(3,4).shape) # a reshaped array
print ()

print ("Original Array's Shape : ", trials.shape) 

[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)

Re-shaped Array : 
 [[10 15 17 26]
 [13 19 12 11]
 [21 24 14 23]]
Re-shaped Array's Shape :  (3, 4)

Original Array's Shape :  (2, 6)


- **Reshape is a function which reshapes the dataset**
- **Here, the dataset is reshaped from 2 rows and 6 columns to 3 rows and 4 columns**
- **It will *not* modify the original array**

In [6]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print (trials)
print ()

print ("Original Array's Shape : ", trials.shape)
print ()

print ("Re-shaped Array : \n", trials.reshape(3,5)) 
print ("Re-shaped Array's Shape : ", trials.reshape(3,5).shape) # a reshaped array
print ()

print ("Original Array's Shape : ", trials.shape) 

[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)



ValueError: cannot reshape array of size 12 into shape (3,5)

In [7]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print (trials)
print ()

print ("Original Array's Shape : ", trials.shape)
print ()

print ("Re-shaped Array : \n", trials.reshape(3,3)) 
print ("Re-shaped Array's Shape : ", trials.reshape(3,3).shape) # a reshaped array
print ()

print ("Original Array's Shape : ", trials.shape) 

[[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)



ValueError: cannot reshape array of size 12 into shape (3,3)

### Resize
This function returns a new array with the specified size.

In [8]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print ("Original Array : \n", trials)
print ()
print ("Original Array's Shape : ", trials.shape) 
print ()

trials.resize(3,4) # no output - updates the original array

print ("Updated Array's Shape : ", trials.shape) 
print ()
print ("Updated Array : \n", trials)

Original Array : 
 [[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)

Updated Array's Shape :  (3, 4)

Updated Array : 
 [[10 15 17 26]
 [13 19 12 11]
 [21 24 14 23]]


- Ravel - Does not update the original array
- Reshape - Does not update the original array
- Resize - **Updates** the original array

In [9]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print ("Original Array : \n", trials)
print ()
print ("Original Array's Shape : ", trials.shape) 
print ()

trials.resize(3,5) # no output - updates the original array

print ("Updated Array's Shape : ", trials.shape) 
print ()
print ("Updated Array : \n", trials)

Original Array : 
 [[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)

Updated Array's Shape :  (3, 5)

Updated Array : 
 [[10 15 17 26 13]
 [19 12 11 21 24]
 [14 23  0  0  0]]


In [10]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print ("Original Array : \n", trials)
print ()
print ("Original Array's Shape : ", trials.shape) 
print ()

trials.resize(3,3) # no output - updates the original array

print ("Updated Array's Shape : ", trials.shape) 
print ()
print ("Updated Array : \n", trials)

Original Array : 
 [[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)

Updated Array's Shape :  (3, 3)

Updated Array : 
 [[10 15 17]
 [26 13 19]
 [12 11 21]]


# Work with same trials - convert it into one col

In [22]:
trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])
print ("Original Array : \n", trials)
print ()
print ("Original Array's Shape : ", trials.shape) 
print ()

trials.resize(trials.size,1) # no output - updates the original array

print ("Updated Array's Shape : ", trials.shape) 
print ()
print ("Updated Array : \n", trials)

Original Array : 
 [[10 15 17 26 13 19]
 [12 11 21 24 14 23]]

Original Array's Shape :  (2, 6)

Updated Array's Shape :  (12, 1)

Updated Array : 
 [[10]
 [15]
 [17]
 [26]
 [13]
 [19]
 [12]
 [11]
 [21]
 [24]
 [14]
 [23]]


In [24]:
A = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [25]:
A[0,1]

15

In [26]:
A[0,0]

10

In [31]:
A[:,[0,3]]

array([[10, 26],
       [12, 24]])

In [32]:
A = np.array(list(range(0,21)))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [33]:
A[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])